name: pomodoro
description: "Pomodoro Timer"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive_ce: ^2.9.0
  hive_ce_flutter: ^2.2.0
  flutter_launcher_icons: ^0.14.3
  flutter_colorpicker: ^1.0.3
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android:true
  ios:true
  image_path:"assets/icon.png"

  # Add your assets here (uncomment and add images when needed)
  # assets:
  #   - assets/logo.png
  #   - assets/sustainability.png
